### PR TITLE
Readonly datetime (part 2 - the saga continues)

### LINKED ISSUE #478: DateTime is still editable when set to readonly
### Expected behavior

The field is disabled.

### Actual behavior

You can edit the field as normal

### Steps to reproduce the problem

```json
"publishedAt": {
  "type": "DateTime",
  "format": "unix",
  "label": "Publish date/time",
  "publish": {
    "section": "Main",
    "placement": "sidebar",
    "readonly": true,
    "display": {
      "edit": true,
      "list": true
    }
  }
}
```

### PR DESCRIPTION
**Pull request by jimlambie**
Fix #478

### CODE REVIEW

File: frontend/components/FieldDateTime/FieldDateTimeEdit.jsx [hunk 1]
```diff
@@ -201,6 +201,12 @@ export default class FieldDateTimeEdit extends Component {
 
   handleFocus(hasFocus) {
     const {pickerVisible} = this.state
+    const {schema} = this.props
+
+    // Return from focus event so picker doesn't display
+    if (schema.publish.readonly === true) {
```
Comment (eduardoboucas) [inline frontend/components/FieldDateTime/FieldDateTimeEdit.jsx]: Is it worth adding a check for `schema.publish`, in case it doesn't exist? I don't think we are ensuring that property exists anywhere upstream.
