### PR TITLE
Document save and other stuff

### LINKED ISSUE #94: Filters no longer working
Filters are appended to the url but are not taking affect

### LINKED ISSUE #99: Save action: incorrect copy
Text should be changed from 'save and duplicate' to 'save _as_ duplicate'

slack-imgs

### LINKED ISSUE #100: Navigation highlighting lost
- [ ] Lost on paginated view
- [ ] Lost in document edit view
slack-imgs-1

### LINKED ISSUE #102: Anchor text clash
Clash when anchor text spans multiline

screen_shot_2017-03-19_at_12 18 23

### LINKED ISSUE #103: Sign-in page rogue pixel
On the sign-in page it is possible to scroll 1 pixel. This reveals a white line. 
slack-imgs-3

### PR DESCRIPTION
**Pull request by eduardoboucas**
This PR:

- Adds document save
- Adds document create
- Adds list view handlers for each API field type (e.g. `FieldStringListView`, `FieldBooleanListView`)
- Adds a WIP version of the bulk actions controller to document list view (needs some refactoring around `SyncTable`)
- Fixes #103
- Fixes #100 
- Fixes #102 
- Fixes #99 
- Fixes #94 
- Adds the favicon

### CODE REVIEW

File: app/lib/controllers/api-bridge.js [hunk 1]
```diff
@@ -57,21 +57,35 @@ APIBridgeController.prototype.post = function (req, res, next) {
...
+          payload.body = JSON.stringify(requestObject.body)
+        }
+
+        return request(payload).then(response => JSON.parse(response))
       }))
     })
 
     Promise.all(queue).then(response => {
-      let output = multiple ? response : response[0]
+      const output = multiple ? response : response[0]
```
Comment (mingard) [inline app/lib/controllers/api-bridge.js]: @eduardoboucas as discussed, `const` inside a method is not supported pre node 6.4 and 4.2 LTS end of support is 1st April 2018

File: frontend/components/FieldString/FieldStringListView.jsx [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+     * The field schema.
+     */
+    schema: proptypes.object
+  }
+
+  constructor(props) {
+    super(props)
+
+    this.MAX_LENGTH = 50
+    this.MAX_OPTIONS = 1
```
Comment (mingard) [inline frontend/components/FieldString/FieldStringListView.jsx]: @eduardoboucas I'd prefer we use default props here.

File: frontend/containers/App/App.jsx [hunk 3]
```diff
@@ -90,7 +91,7 @@ class App extends Component {
     // -- eb, 01/02/2017
 
     return (
-      <div>
+      <div style="height: 100%;">
```
Comment (mingard) [inline frontend/containers/App/App.jsx]: @eduardoboucas are these inline styles WIP?

File: frontend/containers/DocumentList/DocumentList.jsx [hunk 4]
```diff
@@ -168,6 +195,28 @@ class DocumentList extends Component {
     actions.clearDocumentList()
   }
 
+  renderField(fieldName, schema, value) {
```
Comment (mingard) [inline frontend/containers/DocumentList/DocumentList.jsx]: @eduardoboucas I think we need to find a way to stop this being hardcoded. Perhaps not right now, but be aware that we'll have custom fields and they need to be included here

File: app/lib/controllers/api-bridge.js (hunk 1 above)
Comment (eduardoboucas) [inline app/lib/controllers/api-bridge.js]: Sure, I'll change it back.

File: frontend/components/FieldString/FieldStringListView.jsx (hunk 2 above)
Comment (eduardoboucas) [inline frontend/components/FieldString/FieldStringListView.jsx]: Okay.

File: frontend/containers/App/App.jsx (hunk 3 above)
Comment (eduardoboucas) [inline frontend/containers/App/App.jsx]: They can be. App doesn't currently have a style sheet and this is the only styling it'll need, but I'm happy to move it to CSS.

File: frontend/containers/DocumentList/DocumentList.jsx (hunk 4 above)
Comment (eduardoboucas) [inline frontend/containers/DocumentList/DocumentList.jsx]: That will probably involve another endpoint which the front-end will need to ping in order to know which field components are available.

File: frontend/containers/App/App.jsx (hunk 3 above)
Comment (mingard) [inline frontend/containers/App/App.jsx]: @eduardoboucas I think it makes sense to

File: frontend/containers/DocumentList/DocumentList.jsx (hunk 4 above)
Comment (eduardoboucas) [inline frontend/containers/DocumentList/DocumentList.jsx]: Or not! It could be a file written by webpack at build time or something. I can have a play with this as I keep working on document edit.

Comment (mingard) [inline frontend/containers/DocumentList/DocumentList.jsx]: Sure. Let's open a ticket for that for post-mvp.
