### PR TITLE
Fix sorting docs in ReferenceSelectView

### LINKED ISSUE #642: Sorting in reference select view
### Expected behavior

When selecting a document for a reference field, clicking on column headings to sort should sort the documents available for selection

### Actual behavior

When selecting a document for a reference field, clicking on column headings to sort goes back to the parent collection and applies the sort to that

### To reproduce

Use a collection with a reference field
Create a new document
Click "Select new whatever"
Click a column heading to sort

### PR DESCRIPTION
**Pull request by ohmoses**
Closes #642

### CODE REVIEW

File: app/components/DocumentTableList/DocumentTableList.jsx [hunk 1]
```diff
@@ -120,8 +120,8 @@ export default class DocumentTableList extends React.Component {
   }
 
   handleTableSort(value, sortBy, sortOrder) {
-    const {onBuildBaseUrl} = this.props
-    const link = onBuildBaseUrl({
+    const {buildSortUrl = this.props.onBuildBaseUrl} = this.props
```
Comment (eduardoboucas) [inline app/components/DocumentTableList/DocumentTableList.jsx]: Can you clarify this part? Is this so that sorting will use `buildSortUrl` and fall back to `onBuildBaseUrl`?

Comment (ohmoses) [reply app/components/DocumentTableList/DocumentTableList.jsx]: Yes, exactly

**Comment by eduardoboucas** [comment]
Is this good to go?
