### PR TITLE
Make FieldDateTimeFilter use new TextInputWithDatePicker component

### LINKED ISSUE #318: FieldDateTimeFilter/FieldNumberFilter not working
Screencast: https://dadi.slack.com/files/U0DM542GJ/F78ELT34L/fielddatetimefilter_weirdness.mov

Also, the `<select>` needs to be updated to include the `value` prop, as opposed to using `selected` in the individual `<option>` nodes.

### PR DESCRIPTION
**Pull request by eduardoboucas**
Closes #318. Creates #329.

### CODE REVIEW

File: frontend/components/TextInputWithDatePicker/TextInputWithDatePicker.jsx [hunk 1]
```diff
@@ -0,0 +1,243 @@
...
+     * Whether the field is required.
+     *
+     * **NOTE:** This prop is automatically passed down by `<Label/>`.       
+     */
+    required: proptypes.bool,
+
+    /**
+     * Callback to be executed onChange to validate field value.
+     */
+    validation: proptypes.func,
```
Comment (mingard) [inline frontend/components/TextInputWithDatePicker/TextInputWithDatePicker.jsx]: This prop is not used

File: frontend/components/TextInputWithDatePicker/TextInputWithDatePicker.jsx [hunk 2]
```diff
@@ -0,0 +1,243 @@
...
+
+    /**
+     * Callback to be executed when a key is pressed (onKeyUp event).
+     */
+    onKeyUp: proptypes.func,
+
+    /**
+     * Placeholder for the input field.
+     */
+    placeholder: proptypes.string,
```
Comment (mingard) [inline frontend/components/TextInputWithDatePicker/TextInputWithDatePicker.jsx]: This prop is not used

File: frontend/components/TextInputWithDatePicker/TextInputWithDatePicker.jsx [hunk 3]
```diff
@@ -0,0 +1,243 @@
...
+
+    /**
+     * Callback to be executed when the text gains focus (onFocus event).
+     */
+    onFocus: proptypes.func,
+
+    /**
+     * Callback to be executed when a key is pressed (onKeyUp event).
+     */
+    onKeyUp: proptypes.func,
```
Comment (mingard) [inline frontend/components/TextInputWithDatePicker/TextInputWithDatePicker.jsx]: This prop is not used

File: frontend/components/TextInputWithDatePicker/TextInputWithDatePicker.jsx [hunk 4]
```diff
@@ -0,0 +1,243 @@
...
+     * DOM ID for the input field.
+     */
+    id: proptypes.string,
+
+    /**
+     * Whether the field is part of a `<Label/>` component. This makes it inherit certain CSS properties from the parent.
+     *
+     * **NOTE:** This prop is automatically passed down by `<Label/>`.      
+     */
+    inLabel: proptypes.bool,
```
Comment (mingard) [inline frontend/components/TextInputWithDatePicker/TextInputWithDatePicker.jsx]: This prop is not used

File: frontend/components/TextInputWithDatePicker/TextInputWithDatePicker.jsx [hunk 5]
```diff
@@ -0,0 +1,243 @@
...
+     * **NOTE:** This prop is automatically passed down by `<Label/>`.       
+     */
+    readonly: proptypes.bool,
+
+    /**
+     * Whether the field is required.
+     *
+     * **NOTE:** This prop is automatically passed down by `<Label/>`.       
+     */
+    required: proptypes.bool,
```
Comment (mingard) [inline frontend/components/TextInputWithDatePicker/TextInputWithDatePicker.jsx]: This prop is not used

File: frontend/components/TextInputWithDatePicker/TextInputWithDatePicker.jsx [hunk 6]
```diff
@@ -0,0 +1,243 @@
...
+    containerStyle.addResolved(className)
+
+    return (
+      <div class={containerStyle.getClasses()}>
+        <TextInput
+          onBlur={this.handleFocus.bind(this, false)}
+          onChange={this.handleChange.bind(this)}
+          onFocus={this.handleFocus.bind(this, true)}
+          readonly={readonly}
+          type="text"
```
Comment (mingard) [inline frontend/components/TextInputWithDatePicker/TextInputWithDatePicker.jsx]: The default is already text
